using System.Globalization;
using System.Text;
using Tawk.Mcp.Core.Memory;
using Tawk.Mcp.Core.Okf;

namespace Tawk.Mcp.Engines.Knowledge;

public sealed class KnowledgeFormatter : IKnowledgeFormatter
{
    private const string Closing =
        "Inferred observations are guesses from chats, not facts: use them to set tone, never to make claims about a person.";

    public string Observations(IReadOnlyList<ObservationView> observations, int hiddenSensitive, DateTimeOffset now)
    {
        ArgumentNullException.ThrowIfNull(observations);
        var text = new StringBuilder();
        AppendObservations(text, observations, hiddenSensitive, now, true);
        return text.Append(Closing).ToString();
    }

    public string Concept(
        OkfConcept concept, IReadOnlyList<RelatedConcept> relations, IReadOnlyList<ObservationView> observations, int hiddenSensitive, DateTimeOffset now)
    {
        ArgumentNullException.ThrowIfNull(concept);
        ArgumentNullException.ThrowIfNull(relations);
        ArgumentNullException.ThrowIfNull(observations);
        var text = new StringBuilder();
        text.Append(concept.Title ?? concept.Id).Append(" [").Append(concept.Id).Append("]\n");
        text.Append("Type: ").Append(concept.Type).Append(", ").Append(Status(concept.Status)).Append('\n');
        if (!string.IsNullOrWhiteSpace(concept.Description))
        {
            text.Append("Description: ").Append(concept.Description).Append('\n');
        }

        if (concept.Tags.Count > 0)
        {
            text.Append("Tags: ").Append(string.Join(", ", concept.Tags)).Append('\n');
        }

        text.Append(CultureInfo.InvariantCulture, $"Generated by {concept.GeneratedBy} on {concept.GeneratedAt:yyyy-MM-dd}");
        text.Append(concept.Verified.Count == 0 ? ", not verified\n" : ", verified by " + string.Join(", ", concept.Verified.Select(v => v.By).Distinct()) + "\n");
        if (!string.IsNullOrWhiteSpace(concept.Body))
        {
            text.Append('\n').Append(concept.Body.Trim()).Append("\n\n");
        }

        text.Append("Relations:\n");
        if (relations.Count == 0)
        {
            text.Append("  none\n");
        }

        foreach (var relation in relations)
        {
            text.Append("  ").Append(relation.Outgoing ? "this is " : relation.OtherName + " is ").Append(relation.Link.Label).Append(' ')
                .Append(relation.Outgoing ? relation.OtherName : "this").Append(" [").Append(relation.OtherId).Append("] (")
                .Append(OkfExtras.SourceName(relation.Link.Source));
            if (relation.Link.Source is FactSource.Inferred or FactSource.Imported)
            {
                text.Append(CultureInfo.InvariantCulture, $", {relation.Link.Confidence:0.00}");
            }

            text.Append(')');
            if (!string.IsNullOrWhiteSpace(relation.Link.Note))
            {
                text.Append(": ").Append(relation.Link.Note);
            }

            text.Append('\n');
        }

        text.Append("Observations:\n");
        AppendObservations(text, observations, hiddenSensitive, now, false);
        return text.Append(Closing).ToString();
    }

    private static void AppendObservations(StringBuilder text, IReadOnlyList<ObservationView> observations, int hiddenSensitive, DateTimeOffset now, bool showAbout)
    {
        if (observations.Count == 0)
        {
            text.Append(showAbout ? "No observations match.\n" : "  none\n");
        }

        foreach (var view in observations)
        {
            var concept = view.Concept;
            var details = OkfExtras.Read(concept);
            text.Append(showAbout ? string.Empty : "  ").Append('[').Append(concept.Id).Append("] ");
            text.Append(CultureInfo.InvariantCulture, $"{concept.GeneratedAt:yyyy-MM-dd} (").Append(OkfExtras.SourceName(details.Source));
            if (details.Source is FactSource.Inferred or FactSource.Imported)
            {
                text.Append(CultureInfo.InvariantCulture, $", {details.Confidence:0.00}");
            }

            if (details.Sensitive)
            {
                text.Append(", sensitive");
            }

            if (concept.StaleAfter is { } stale)
            {
                text.Append(stale <= now ? ", stale" : string.Create(CultureInfo.InvariantCulture, $", until {stale:yyyy-MM-dd}"));
            }

            text.Append(')');
            if (showAbout && view.About.Count > 0)
            {
                text.Append(" about ").Append(string.Join(", ", view.About));
            }

            if (concept.Tags.Count > 0)
            {
                text.Append(" #").Append(string.Join(" #", concept.Tags));
            }

            text.Append(": ").Append(concept.Body).Append('\n');
        }

        if (hiddenSensitive > 0)
        {
            text.Append(CultureInfo.InvariantCulture, $"{(showAbout ? string.Empty : "  ")}{hiddenSensitive} sensitive observation(s) hidden; ask with include_sensitive only if the user wants them.\n");
        }
    }

    private static string Status(OkfStatus status) => status switch
    {
        OkfStatus.Draft => "draft",
        OkfStatus.Deprecated => "deprecated",
        _ => "stable",
    };
}
